spring:
  application:
    name: config-server
  profiles:
    #active: native
    active: git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/AlexanderBessonov/Ticketing-Project-Microservices-Config-Alexander
          default-label: master
          username: AlexanderBessonov
          password: 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
      fail-fast: true
        #native:
          #search-locations: classpath:/config

server:
  port: 8888
